### ISSUE TITLE
Update edit and edited views to have the option encrypt and decrypt password

### ISSUE THREAD

**Issue by izorakayumova** [michellengnx/csc207-project#40]
Possibly think of adding a feature to the edit and edited views, which showcases the details of the editable parameters to a patient's profile, to hide and unhide a patient's password.

- [x] implement this feature similarly to how it would be in signup and login view
- [x] discuss if other features would look better encrypted like cvv in CreditCard and insurance

**Comment by michellengnx** [comment]
Look into salting and hashing. Bcrypt could also be a good solution for properly and securely storing user's password

**Comment by izorakayumova** [comment]
@michellengnx I implemented this feature in editview by making a showPasswordCheckbox as JPasswordField already hides the password when typed in by a user. Lemme know if you're going to do something similar for signup and loginview

**Comment by michellengnx** [comment]
I am doing something similar in my use case. We can discuss later if we want to refactor that into a separate common component so both of us can use it and avoid repeating code.

**Comment by izorakayumova** [comment]
update:
- successfully implemented a show password checkbox in edit view, sign up view and login view
- made new label classes for cvv and other parameters that needed specific formatting
